version: '3.8'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
    networks:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
#    restart: always
    ports:
      - 8082:80
    environment:
#      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: my_root_password  # No need
      # We don't need PMA_USER & PMA_PASSWORD if we provide MYSQL_ROOT_PASSWORD. Otherwise we do.
#      PMA_USER: username
#      PMA_PASSWORD: password
    volumes:
      - /sessions
    networks:
      - mariadb
    depends_on:
      - mariadb

#  adminer:
#    image: adminer:latest
#    container_name: adminer
##    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - mariadb
#    depends_on:
#      - mariadb

networks:
  mariadb:

volumes:
  mariadb_data:
